"""Создал таблицы

Revision ID: 6cce955a5cbb
Revises: 9d870f7c93da
Create Date: 2025-08-20 20:05:03.406440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cce955a5cbb'
down_revision: Union[str, Sequence[str], None] = '9d870f7c93da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'category_id')
    # ### end Alembic commands ###
