"""Add ondelete=CASCADE in Service

Revision ID: 6f534a434fbd
Revises: c0617eec74f4
Create Date: 2025-08-23 15:40:56.536200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f534a434fbd'
down_revision: Union[str, Sequence[str], None] = 'c0617eec74f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('services_category_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'categories', ['category_id'], ['category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_category_id_fkey'), 'services', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###
