"""Изменил название переменных в моделях

Revision ID: b8791cf06134
Revises: 6cce955a5cbb
Create Date: 2025-08-22 12:44:00.288856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8791cf06134'
down_revision: Union[str, Sequence[str], None] = '6cce955a5cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.drop_table('clients')
    op.add_column('categories', sa.Column('category_name', sa.String(), nullable=False))
    op.add_column('categories', sa.Column('category_description', sa.String(), nullable=True))
    op.drop_column('categories', 'name')
    op.drop_column('categories', 'description')
    op.add_column('services', sa.Column('service_name', sa.String(), nullable=False))
    op.add_column('services', sa.Column('service_description', sa.String(), nullable=True))
    op.add_column('services', sa.Column('service_price', sa.Integer(), nullable=True))
    op.drop_column('services', 'price')
    op.drop_column('services', 'name')
    op.drop_column('services', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('services', 'service_price')
    op.drop_column('services', 'service_description')
    op.drop_column('services', 'service_name')
    op.add_column('categories', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'category_description')
    op.drop_column('categories', 'category_name')
    op.create_table('clients',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('user', 'admin', name='userrole'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('clients_pkey'))
    )
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
