"""Вернул название таблиц

Revision ID: c0617eec74f4
Revises: 3bc9605057f7
Create Date: 2025-08-22 20:00:06.374535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0617eec74f4'
down_revision: Union[str, Sequence[str], None] = '3bc9605057f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(), nullable=False))
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('categories', 'category_description')
    op.drop_column('categories', 'category_name')
    op.add_column('services', sa.Column('name', sa.String(), nullable=False))
    op.add_column('services', sa.Column('description', sa.String(), nullable=True))
    op.add_column('services', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('services', 'service_description')
    op.drop_column('services', 'service_price')
    op.drop_column('services', 'service_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('service_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('service_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('services', 'price')
    op.drop_column('services', 'description')
    op.drop_column('services', 'name')
    op.add_column('categories', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('category_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'description')
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
